### ISSUE TITLE
librarian-puppet install step fails partially 

### ISSUE THREAD

**Issue by cmadsen** [carlossg/puppet-for-java-devs#1]
$ librarian-puppet install
/usr/share/rubygems/rubygems/custom_require.rb:55:in `require': iconv will be deprecated in the future, use String#encode instead.
/usr/share/rubygems/rubygems/custom_require.rb:36:in`require': iconv will be deprecated in the future, use String#encode instead.
/usr/share/rubygems/rubygems/custom_require.rb:36:in `require': iconv will be deprecated in the future, use String#encode instead.
/usr/share/rubygems/rubygems/custom_require.rb:36:in`require': iconv will be deprecated in the future, use String#encode instead.
/usr/share/rubygems/rubygems/custom_require.rb:36:in `require': iconv will be deprecated in the future, use String#encode instead.
/usr/share/rubygems/rubygems/custom_require.rb:36:in`require': iconv will be deprecated in the future, use String#encode instead.
/usr/share/rubygems/rubygems/custom_require.rb:36:in `require': iconv will be deprecated in the future, use String#encode instead.
Error: No such file or directory - /opt/puppet-for-java-devs/.tmp/librarian/cache/source/puppet/forge/3792e516e3ff92a0ef9f5e827f8e76eb/puppetlabs/apache/version/9eac01120a372609e0afa3b236d9ed2d/apache/spec/fixtures/modules/apache
Error: Try 'puppet help module install' for usage

I think this later on causes the apache stuff to fail

$ uname -a
Linux 3.5.3-1.fc17.i686.PAE #1 SMP

**Comment by aussielunix** [comment]
@cmadsen What version of ruby is this running under ?
I suspect you are using 1.9.3.
Because librarian-puppet is just an extension to [librarian](https://github.com/applicationsonline/librarian) we are stuck running the version of ruby it requires.

I have been using 1.9.2-p290 without any troubles.

**Comment by cmadsen** [comment]
ruby -v
ruby 1.9.3p194 (2012-04-20 revision 35410) [i386-linux]

So do I need to run 1.9.2-p290 to get rid of:

Error: No such file or directory - /opt/puppet-for-java-devs/.tmp/librarian/cache/source/puppet/forge/3792e516e3ff92a0ef9f5e827f8e76eb/puppetlabs/apache/version/9eac01120a372609e0afa3b236d9ed2d/apache/spec/fixtures/modules/apache

?

**Comment by alrighttheresham** [comment]
Hi Guys any update on this issue, same problem on OSX.  

[damianoneill puppet-for-java-devs]$ ruby -v
ruby 1.9.3p327 (2012-11-10 revision 37606) [x86_64-darwin12]
[damianoneill puppet-for-java-devs]$

**Comment by carlossg** [comment]
I have pushed a commit using our fork of librarian-puppet-maestrodev, that has several fixes not yet merged. Working for me on OS X ruby 1.9.3p327
